// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: github/v1/exchange.proto

package githubv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Token struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	ExpiresIn     *durationpb.Duration   `protobuf:"bytes,2,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Token) Reset() {
	*x = Token{}
	mi := &file_github_v1_exchange_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Token) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Token) ProtoMessage() {}

func (x *Token) ProtoReflect() protoreflect.Message {
	mi := &file_github_v1_exchange_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Token.ProtoReflect.Descriptor instead.
func (*Token) Descriptor() ([]byte, []int) {
	return file_github_v1_exchange_proto_rawDescGZIP(), []int{0}
}

func (x *Token) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Token) GetExpiresIn() *durationpb.Duration {
	if x != nil {
		return x.ExpiresIn
	}
	return nil
}

type Account struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Login        string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Id           uint32                 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	NodeId       string                 `protobuf:"bytes,3,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	GravatarId   string                 `protobuf:"bytes,4,opt,name=gravatar_id,json=gravatarId,proto3" json:"gravatar_id,omitempty"`
	Urls         *Account_URLs          `protobuf:"bytes,5,opt,name=urls,proto3" json:"urls,omitempty"`
	Type         string                 `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"`
	UserViewType string                 `protobuf:"bytes,7,opt,name=user_view_type,json=userViewType,proto3" json:"user_view_type,omitempty"`
	SiteAdmin    bool                   `protobuf:"varint,8,opt,name=site_admin,json=siteAdmin,proto3" json:"site_admin,omitempty"`
	Name         string                 `protobuf:"bytes,9,opt,name=name,proto3" json:"name,omitempty"`
	// company
	Blog string `protobuf:"bytes,11,opt,name=blog,proto3" json:"blog,omitempty"`
	// location
	Email string `protobuf:"bytes,13,opt,name=email,proto3" json:"email,omitempty"`
	// hireable
	// bio
	// twitter_username
	NotificationEmail string                 `protobuf:"bytes,17,opt,name=notification_email,json=notificationEmail,proto3" json:"notification_email,omitempty"`
	PublicRepos       uint32                 `protobuf:"varint,18,opt,name=public_repos,json=publicRepos,proto3" json:"public_repos,omitempty"`
	PublicGists       uint32                 `protobuf:"varint,19,opt,name=public_gists,json=publicGists,proto3" json:"public_gists,omitempty"`
	Followers         uint32                 `protobuf:"varint,20,opt,name=followers,proto3" json:"followers,omitempty"`
	Following         uint32                 `protobuf:"varint,21,opt,name=following,proto3" json:"following,omitempty"`
	CreatedAt         *timestamppb.Timestamp `protobuf:"bytes,22,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt         *timestamppb.Timestamp `protobuf:"bytes,23,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_github_v1_exchange_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_github_v1_exchange_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_github_v1_exchange_proto_rawDescGZIP(), []int{1}
}

func (x *Account) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *Account) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Account) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Account) GetGravatarId() string {
	if x != nil {
		return x.GravatarId
	}
	return ""
}

func (x *Account) GetUrls() *Account_URLs {
	if x != nil {
		return x.Urls
	}
	return nil
}

func (x *Account) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Account) GetUserViewType() string {
	if x != nil {
		return x.UserViewType
	}
	return ""
}

func (x *Account) GetSiteAdmin() bool {
	if x != nil {
		return x.SiteAdmin
	}
	return false
}

func (x *Account) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Account) GetBlog() string {
	if x != nil {
		return x.Blog
	}
	return ""
}

func (x *Account) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Account) GetNotificationEmail() string {
	if x != nil {
		return x.NotificationEmail
	}
	return ""
}

func (x *Account) GetPublicRepos() uint32 {
	if x != nil {
		return x.PublicRepos
	}
	return 0
}

func (x *Account) GetPublicGists() uint32 {
	if x != nil {
		return x.PublicGists
	}
	return 0
}

func (x *Account) GetFollowers() uint32 {
	if x != nil {
		return x.Followers
	}
	return 0
}

func (x *Account) GetFollowing() uint32 {
	if x != nil {
		return x.Following
	}
	return 0
}

func (x *Account) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Account) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ExchangeRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	ClientId string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Code     string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	// If set, resulting access token will also be resolved to an `Account`.
	Resolve       bool `protobuf:"varint,3,opt,name=resolve,proto3" json:"resolve,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExchangeRequest) Reset() {
	*x = ExchangeRequest{}
	mi := &file_github_v1_exchange_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeRequest) ProtoMessage() {}

func (x *ExchangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_v1_exchange_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeRequest.ProtoReflect.Descriptor instead.
func (*ExchangeRequest) Descriptor() ([]byte, []int) {
	return file_github_v1_exchange_proto_rawDescGZIP(), []int{2}
}

func (x *ExchangeRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ExchangeRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ExchangeRequest) GetResolve() bool {
	if x != nil {
		return x.Resolve
	}
	return false
}

type ExchangeResponse struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	AccessToken  *Token                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken *Token                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	TokenType    string                 `protobuf:"bytes,3,opt,name=token_type,json=tokenType,proto3" json:"token_type,omitempty"`
	Scope        string                 `protobuf:"bytes,4,opt,name=scope,proto3" json:"scope,omitempty"`
	// Only set if `ExchangeRequest.resolve` is true.
	Account       *Account `protobuf:"bytes,5,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExchangeResponse) Reset() {
	*x = ExchangeResponse{}
	mi := &file_github_v1_exchange_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeResponse) ProtoMessage() {}

func (x *ExchangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_v1_exchange_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeResponse.ProtoReflect.Descriptor instead.
func (*ExchangeResponse) Descriptor() ([]byte, []int) {
	return file_github_v1_exchange_proto_rawDescGZIP(), []int{3}
}

func (x *ExchangeResponse) GetAccessToken() *Token {
	if x != nil {
		return x.AccessToken
	}
	return nil
}

func (x *ExchangeResponse) GetRefreshToken() *Token {
	if x != nil {
		return x.RefreshToken
	}
	return nil
}

func (x *ExchangeResponse) GetTokenType() string {
	if x != nil {
		return x.TokenType
	}
	return ""
}

func (x *ExchangeResponse) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *ExchangeResponse) GetAccount() *Account {
	if x != nil {
		return x.Account
	}
	return nil
}

type RefreshRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	ClientId     string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	RefreshToken string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	// If set, resulting access token will also be resolved to an `Account`.
	Resolve       bool `protobuf:"varint,3,opt,name=resolve,proto3" json:"resolve,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshRequest) Reset() {
	*x = RefreshRequest{}
	mi := &file_github_v1_exchange_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshRequest) ProtoMessage() {}

func (x *RefreshRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_v1_exchange_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshRequest.ProtoReflect.Descriptor instead.
func (*RefreshRequest) Descriptor() ([]byte, []int) {
	return file_github_v1_exchange_proto_rawDescGZIP(), []int{4}
}

func (x *RefreshRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *RefreshRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *RefreshRequest) GetResolve() bool {
	if x != nil {
		return x.Resolve
	}
	return false
}

type RefreshResponse struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	AccessToken *Token                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	TokenType   string                 `protobuf:"bytes,2,opt,name=token_type,json=tokenType,proto3" json:"token_type,omitempty"`
	Scope       string                 `protobuf:"bytes,3,opt,name=scope,proto3" json:"scope,omitempty"`
	// Only set if `RefreshRequest.resolve` is true.
	Account       *Account `protobuf:"bytes,5,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshResponse) Reset() {
	*x = RefreshResponse{}
	mi := &file_github_v1_exchange_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshResponse) ProtoMessage() {}

func (x *RefreshResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_v1_exchange_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshResponse.ProtoReflect.Descriptor instead.
func (*RefreshResponse) Descriptor() ([]byte, []int) {
	return file_github_v1_exchange_proto_rawDescGZIP(), []int{5}
}

func (x *RefreshResponse) GetAccessToken() *Token {
	if x != nil {
		return x.AccessToken
	}
	return nil
}

func (x *RefreshResponse) GetTokenType() string {
	if x != nil {
		return x.TokenType
	}
	return ""
}

func (x *RefreshResponse) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *RefreshResponse) GetAccount() *Account {
	if x != nil {
		return x.Account
	}
	return nil
}

type ResolveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveRequest) Reset() {
	*x = ResolveRequest{}
	mi := &file_github_v1_exchange_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveRequest) ProtoMessage() {}

func (x *ResolveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_v1_exchange_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveRequest.ProtoReflect.Descriptor instead.
func (*ResolveRequest) Descriptor() ([]byte, []int) {
	return file_github_v1_exchange_proto_rawDescGZIP(), []int{6}
}

func (x *ResolveRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type ResolveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       *Account               `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveResponse) Reset() {
	*x = ResolveResponse{}
	mi := &file_github_v1_exchange_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveResponse) ProtoMessage() {}

func (x *ResolveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_v1_exchange_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveResponse.ProtoReflect.Descriptor instead.
func (*ResolveResponse) Descriptor() ([]byte, []int) {
	return file_github_v1_exchange_proto_rawDescGZIP(), []int{7}
}

func (x *ResolveResponse) GetAccount() *Account {
	if x != nil {
		return x.Account
	}
	return nil
}

type Account_URLs struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Avatar         string                 `protobuf:"bytes,1,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Api            string                 `protobuf:"bytes,2,opt,name=api,proto3" json:"api,omitempty"`
	Html           string                 `protobuf:"bytes,3,opt,name=html,proto3" json:"html,omitempty"`
	Followers      string                 `protobuf:"bytes,4,opt,name=followers,proto3" json:"followers,omitempty"`
	Following      string                 `protobuf:"bytes,5,opt,name=following,proto3" json:"following,omitempty"`
	Gists          string                 `protobuf:"bytes,6,opt,name=gists,proto3" json:"gists,omitempty"`
	Starred        string                 `protobuf:"bytes,7,opt,name=starred,proto3" json:"starred,omitempty"`
	Subscriptions  string                 `protobuf:"bytes,8,opt,name=subscriptions,proto3" json:"subscriptions,omitempty"`
	Organizations  string                 `protobuf:"bytes,9,opt,name=organizations,proto3" json:"organizations,omitempty"`
	Repos          string                 `protobuf:"bytes,10,opt,name=repos,proto3" json:"repos,omitempty"`
	Events         string                 `protobuf:"bytes,11,opt,name=events,proto3" json:"events,omitempty"`
	ReceivedEvents string                 `protobuf:"bytes,12,opt,name=received_events,json=receivedEvents,proto3" json:"received_events,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Account_URLs) Reset() {
	*x = Account_URLs{}
	mi := &file_github_v1_exchange_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account_URLs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account_URLs) ProtoMessage() {}

func (x *Account_URLs) ProtoReflect() protoreflect.Message {
	mi := &file_github_v1_exchange_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account_URLs.ProtoReflect.Descriptor instead.
func (*Account_URLs) Descriptor() ([]byte, []int) {
	return file_github_v1_exchange_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Account_URLs) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *Account_URLs) GetApi() string {
	if x != nil {
		return x.Api
	}
	return ""
}

func (x *Account_URLs) GetHtml() string {
	if x != nil {
		return x.Html
	}
	return ""
}

func (x *Account_URLs) GetFollowers() string {
	if x != nil {
		return x.Followers
	}
	return ""
}

func (x *Account_URLs) GetFollowing() string {
	if x != nil {
		return x.Following
	}
	return ""
}

func (x *Account_URLs) GetGists() string {
	if x != nil {
		return x.Gists
	}
	return ""
}

func (x *Account_URLs) GetStarred() string {
	if x != nil {
		return x.Starred
	}
	return ""
}

func (x *Account_URLs) GetSubscriptions() string {
	if x != nil {
		return x.Subscriptions
	}
	return ""
}

func (x *Account_URLs) GetOrganizations() string {
	if x != nil {
		return x.Organizations
	}
	return ""
}

func (x *Account_URLs) GetRepos() string {
	if x != nil {
		return x.Repos
	}
	return ""
}

func (x *Account_URLs) GetEvents() string {
	if x != nil {
		return x.Events
	}
	return ""
}

func (x *Account_URLs) GetReceivedEvents() string {
	if x != nil {
		return x.ReceivedEvents
	}
	return ""
}

var File_github_v1_exchange_proto protoreflect.FileDescriptor

const file_github_v1_exchange_proto_rawDesc = "" +
	"\n" +
	"\x18github/v1/exchange.proto\x12\tgithub.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"W\n" +
	"\x05Token\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x128\n" +
	"\n" +
	"expires_in\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\texpiresIn\"\xaa\a\n" +
	"\aAccount\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\rR\x02id\x12\x17\n" +
	"\anode_id\x18\x03 \x01(\tR\x06nodeId\x12\x1f\n" +
	"\vgravatar_id\x18\x04 \x01(\tR\n" +
	"gravatarId\x12+\n" +
	"\x04urls\x18\x05 \x01(\v2\x17.github.v1.Account.URLsR\x04urls\x12\x12\n" +
	"\x04type\x18\x06 \x01(\tR\x04type\x12$\n" +
	"\x0euser_view_type\x18\a \x01(\tR\fuserViewType\x12\x1d\n" +
	"\n" +
	"site_admin\x18\b \x01(\bR\tsiteAdmin\x12\x12\n" +
	"\x04name\x18\t \x01(\tR\x04name\x12\x12\n" +
	"\x04blog\x18\v \x01(\tR\x04blog\x12\x14\n" +
	"\x05email\x18\r \x01(\tR\x05email\x12-\n" +
	"\x12notification_email\x18\x11 \x01(\tR\x11notificationEmail\x12!\n" +
	"\fpublic_repos\x18\x12 \x01(\rR\vpublicRepos\x12!\n" +
	"\fpublic_gists\x18\x13 \x01(\rR\vpublicGists\x12\x1c\n" +
	"\tfollowers\x18\x14 \x01(\rR\tfollowers\x12\x1c\n" +
	"\tfollowing\x18\x15 \x01(\rR\tfollowing\x129\n" +
	"\n" +
	"created_at\x18\x16 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x17 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x1a\xd3\x02\n" +
	"\x04URLs\x12\x16\n" +
	"\x06avatar\x18\x01 \x01(\tR\x06avatar\x12\x10\n" +
	"\x03api\x18\x02 \x01(\tR\x03api\x12\x12\n" +
	"\x04html\x18\x03 \x01(\tR\x04html\x12\x1c\n" +
	"\tfollowers\x18\x04 \x01(\tR\tfollowers\x12\x1c\n" +
	"\tfollowing\x18\x05 \x01(\tR\tfollowing\x12\x14\n" +
	"\x05gists\x18\x06 \x01(\tR\x05gists\x12\x18\n" +
	"\astarred\x18\a \x01(\tR\astarred\x12$\n" +
	"\rsubscriptions\x18\b \x01(\tR\rsubscriptions\x12$\n" +
	"\rorganizations\x18\t \x01(\tR\rorganizations\x12\x14\n" +
	"\x05repos\x18\n" +
	" \x01(\tR\x05repos\x12\x16\n" +
	"\x06events\x18\v \x01(\tR\x06events\x12'\n" +
	"\x0freceived_events\x18\f \x01(\tR\x0ereceivedEvents\"l\n" +
	"\x0fExchangeRequest\x12#\n" +
	"\tclient_id\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\bclientId\x12\x1a\n" +
	"\x04code\x18\x02 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x04code\x12\x18\n" +
	"\aresolve\x18\x03 \x01(\bR\aresolve\"\xe1\x01\n" +
	"\x10ExchangeResponse\x123\n" +
	"\faccess_token\x18\x01 \x01(\v2\x10.github.v1.TokenR\vaccessToken\x125\n" +
	"\rrefresh_token\x18\x02 \x01(\v2\x10.github.v1.TokenR\frefreshToken\x12\x1d\n" +
	"\n" +
	"token_type\x18\x03 \x01(\tR\ttokenType\x12\x14\n" +
	"\x05scope\x18\x04 \x01(\tR\x05scope\x12,\n" +
	"\aaccount\x18\x05 \x01(\v2\x12.github.v1.AccountR\aaccount\"|\n" +
	"\x0eRefreshRequest\x12#\n" +
	"\tclient_id\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\bclientId\x12+\n" +
	"\rrefresh_token\x18\x02 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\frefreshToken\x12\x18\n" +
	"\aresolve\x18\x03 \x01(\bR\aresolve\"\xa9\x01\n" +
	"\x0fRefreshResponse\x123\n" +
	"\faccess_token\x18\x01 \x01(\v2\x10.github.v1.TokenR\vaccessToken\x12\x1d\n" +
	"\n" +
	"token_type\x18\x02 \x01(\tR\ttokenType\x12\x14\n" +
	"\x05scope\x18\x03 \x01(\tR\x05scope\x12,\n" +
	"\aaccount\x18\x05 \x01(\v2\x12.github.v1.AccountR\aaccount\"3\n" +
	"\x0eResolveRequest\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\"?\n" +
	"\x0fResolveResponse\x12,\n" +
	"\aaccount\x18\x02 \x01(\v2\x12.github.v1.AccountR\aaccount2\xda\x01\n" +
	"\x0fExchangeService\x12C\n" +
	"\bExchange\x12\x1a.github.v1.ExchangeRequest\x1a\x1b.github.v1.ExchangeResponse\x12@\n" +
	"\aRefresh\x12\x19.github.v1.RefreshRequest\x1a\x1a.github.v1.RefreshResponse\x12@\n" +
	"\aResolve\x12\x19.github.v1.ResolveRequest\x1a\x1a.github.v1.ResolveResponseB\xa8\x01\n" +
	"\rcom.github.v1B\rExchangeProtoP\x01ZCgithub.com/roboslone/github-oauth-exchange/proto/github/v1;githubv1\xa2\x02\x03GXX\xaa\x02\tGithub.V1\xca\x02\tGithub\\V1\xe2\x02\x15Github\\V1\\GPBMetadata\xea\x02\n" +
	"Github::V1b\x06proto3"

var (
	file_github_v1_exchange_proto_rawDescOnce sync.Once
	file_github_v1_exchange_proto_rawDescData []byte
)

func file_github_v1_exchange_proto_rawDescGZIP() []byte {
	file_github_v1_exchange_proto_rawDescOnce.Do(func() {
		file_github_v1_exchange_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_github_v1_exchange_proto_rawDesc), len(file_github_v1_exchange_proto_rawDesc)))
	})
	return file_github_v1_exchange_proto_rawDescData
}

var file_github_v1_exchange_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_github_v1_exchange_proto_goTypes = []any{
	(*Token)(nil),                 // 0: github.v1.Token
	(*Account)(nil),               // 1: github.v1.Account
	(*ExchangeRequest)(nil),       // 2: github.v1.ExchangeRequest
	(*ExchangeResponse)(nil),      // 3: github.v1.ExchangeResponse
	(*RefreshRequest)(nil),        // 4: github.v1.RefreshRequest
	(*RefreshResponse)(nil),       // 5: github.v1.RefreshResponse
	(*ResolveRequest)(nil),        // 6: github.v1.ResolveRequest
	(*ResolveResponse)(nil),       // 7: github.v1.ResolveResponse
	(*Account_URLs)(nil),          // 8: github.v1.Account.URLs
	(*durationpb.Duration)(nil),   // 9: google.protobuf.Duration
	(*timestamppb.Timestamp)(nil), // 10: google.protobuf.Timestamp
}
var file_github_v1_exchange_proto_depIdxs = []int32{
	9,  // 0: github.v1.Token.expires_in:type_name -> google.protobuf.Duration
	8,  // 1: github.v1.Account.urls:type_name -> github.v1.Account.URLs
	10, // 2: github.v1.Account.created_at:type_name -> google.protobuf.Timestamp
	10, // 3: github.v1.Account.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 4: github.v1.ExchangeResponse.access_token:type_name -> github.v1.Token
	0,  // 5: github.v1.ExchangeResponse.refresh_token:type_name -> github.v1.Token
	1,  // 6: github.v1.ExchangeResponse.account:type_name -> github.v1.Account
	0,  // 7: github.v1.RefreshResponse.access_token:type_name -> github.v1.Token
	1,  // 8: github.v1.RefreshResponse.account:type_name -> github.v1.Account
	1,  // 9: github.v1.ResolveResponse.account:type_name -> github.v1.Account
	2,  // 10: github.v1.ExchangeService.Exchange:input_type -> github.v1.ExchangeRequest
	4,  // 11: github.v1.ExchangeService.Refresh:input_type -> github.v1.RefreshRequest
	6,  // 12: github.v1.ExchangeService.Resolve:input_type -> github.v1.ResolveRequest
	3,  // 13: github.v1.ExchangeService.Exchange:output_type -> github.v1.ExchangeResponse
	5,  // 14: github.v1.ExchangeService.Refresh:output_type -> github.v1.RefreshResponse
	7,  // 15: github.v1.ExchangeService.Resolve:output_type -> github.v1.ResolveResponse
	13, // [13:16] is the sub-list for method output_type
	10, // [10:13] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_github_v1_exchange_proto_init() }
func file_github_v1_exchange_proto_init() {
	if File_github_v1_exchange_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_v1_exchange_proto_rawDesc), len(file_github_v1_exchange_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_github_v1_exchange_proto_goTypes,
		DependencyIndexes: file_github_v1_exchange_proto_depIdxs,
		MessageInfos:      file_github_v1_exchange_proto_msgTypes,
	}.Build()
	File_github_v1_exchange_proto = out.File
	file_github_v1_exchange_proto_goTypes = nil
	file_github_v1_exchange_proto_depIdxs = nil
}
